// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJap96oRxtV-MDkaay1dh-yd9K7_rshhE',
    appId: '1:858845455421:web:8e88bb921e45c278837654',
    messagingSenderId: '858845455421',
    projectId: 'padelapp-7bc59',
    authDomain: 'padelapp-7bc59.firebaseapp.com',
    storageBucket: 'padelapp-7bc59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnnPj9aOvXahe1Zxi0fNLD1UIPrRaviu0',
    appId: '1:858845455421:android:c995ca6f4a688335837654',
    messagingSenderId: '858845455421',
    projectId: 'padelapp-7bc59',
    storageBucket: 'padelapp-7bc59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlaJ2GN4RJVoH6UeaelAHxYoXzFEGWdMA',
    appId: '1:858845455421:ios:c36184b76bf8e744837654',
    messagingSenderId: '858845455421',
    projectId: 'padelapp-7bc59',
    storageBucket: 'padelapp-7bc59.appspot.com',
    iosBundleId: 'com.example.padelApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlaJ2GN4RJVoH6UeaelAHxYoXzFEGWdMA',
    appId: '1:858845455421:ios:794b36d3b9215dd2837654',
    messagingSenderId: '858845455421',
    projectId: 'padelapp-7bc59',
    storageBucket: 'padelapp-7bc59.appspot.com',
    iosBundleId: 'com.example.padelApplication.RunnerTests',
  );
}
